services:
  api:
    build: .
    ports: 
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://ecommerce:ecommerce@postgres:5432/ecommerce
  postgres:
    image: postgres:17
    environment: 
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  postgres_test:
    image: postgres:17
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce_test

volumes:
  postgres_data: