services:
  api:
    build: .
    ports: 
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ecommerce:ecommerce@postgres:5432/ecommerce
  postgres:
    image: postgres:17
    environment: 
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data: